# Site settings
baseurl = "https://opensourcewriter.com/"
languageCode = "en-us"
title = "Open Source Writer"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Open Source Writer"
	author = "S.M. Oliva"
	description = "A blog highlighting software applications for the Solus operating system"
	bio = "A Mystical Journey Through the Solus Software Center"
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "Legal"
	subscribe = "RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "Open Source Writer by [S.M. Oliva](https://skipoliva.com) is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/)."
	# Sharing options and author information in posts
  aboutAuthor = "By S.M. Oliva"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    github   = "https://www.github.com/oswriter"
