baseurl = "https://opensourcewriter.com/"
title = "Open Source Writer"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
    name = "S.M. Oliva"
    bio = "I have over 16 years experience writing for the web. Currently I ghostwrite content for more than a dozen law blogs, covering subjects from personal injury and bankruptcy to criminal defense and intellectual property."
    avatar = "images/inn.jpg"

[Params]
    subtitle = "Solus is Life" # Subtitle of your site
    description = "A guide to using software on Solus, a Linux-based operating system" # Description of your site
    opengraph = true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = false # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
    social_facebook = ""
    social_twitter = ""
    social_linkedin = ""
    social_github = "oswriter"
    social_email = "smo@skipoliva.com"
