baseurl = "https://opensourcewriter.com"
title = "Open Source Writer"
author = "S.M. Oliva"
paginate = 10
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "Solus Is Life"
    description = "A blog covering Solus, a Linux-based operating system, and other subjects related to open source software" # Description of your site
    authorbox = true
    author = "S.M. Oliva"
    post_navigation = false
    alert = "Solus 3 was released on August 15, 2017! Download it [here](https://solus-project.com/download/)."

[Params.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#4C5164"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#5090DD"
    accent_text = "#e2e2e2"

[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = false
    tags_counter = false
    patreon = ""

[Params.social]
    github = "oswriter"
    googleplus = "u/1/114649717339477494492"
    telegram = "oswriter"
    youtube = "playlist?list=PL-SnlI1M7z9vbL31r0Q3JuCWkw9i7_7yN"

[menu]
