baseurl = "https://bluestnight.shadow53.com"
title = "BluestNight"
author = "Michael Bryant"
paginate = 10
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "A featureful, configurable, yet sleek dark theme for Hugo."
    description = "The official example website for the BluestNight Hugo theme. Comes with documentation." # Description of your site
    authorbox = true
    author = "Some Guy"
    post_navigation = false
    alert = "Subscribe to my [programming blog's](https://shadow53.com) RSS feed to be notified of updates to this theme."

[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = true
    tags_counter = true
    patreon = "shadow53"

[Params.social]
    gitlab = "Shadow53/BluestNight"

[menu]
      [[menu.main]]
        name = "Alert"
        weight = 1
        parent = "docs-pages"
        identifier = "alert-for-pages"
        url = "docs/site/alert/#page-specific-alerts"
      [[menu.main]]
        name = "Alert"
        weight = 1
        parent = "docs-shortcodes"
        identifier = "alert-shortcode"
        url = "docs/site/alert/#shortcode"
      [[menu.main]]
        name = "Responsive Tables"
        weight = 4
        parent = "docs-shortcodes"
        identifier = "table-shortcode"
        url = "docs/pages/responsive-tables/"
  [[menu.main]]
    name = "Tutorials"
    weight = 10
    identifier = "tutorials"
    url = "#"
